-- MEMBER_PROFILE
SELECT M.MEMBER_NAME, RC.REVIEW_TEXT, RC.REVIEW_DATE
FROM MEMBER_PROFILE M
JOIN (
    SELECT R.MEMBER_ID, R.REVIEW_TEXT, TO_CHAR(R.REVIEW_DATE, 'YYYY-MM-DD') REVIEW_DATE
    FROM REST_REVIEW R
    JOIN (
        SELECT MEMBER_ID
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        HAVING COUNT(MEMBER_ID) = (
            SELECT CT.C
            FROM (
                SELECT COUNT(MEMBER_ID) C
                FROM REST_REVIEW 
                GROUP BY MEMBER_ID
                ORDER BY C DESC
            ) CT
        	WHERE ROWNUM < 2
        )
	) B
	ON R.MEMBER_ID = B.MEMBER_ID
) RC
ON M.MEMBER_ID = RC.MEMBER_ID
;

SELECT MEMBER_ID
FROM REST_REVIEW
GROUP BY MEMBER_ID
HAVING COUNT(MEMBER_ID) = (
    SELECT CT.C
    FROM (
        SELECT COUNT(MEMBER_ID) C
        FROM REST_REVIEW 
        GROUP BY MEMBER_ID
        ORDER BY C DESC
    ) CT
	WHERE ROWNUM < 2
)
